language: php

php:
  - '5.6'
  - '7.0'

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  - composer info -i

script:
  - ./vendor/bin/phpunit
