language: php

php:
  - '5.3'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  - composer info -i

script:
  - ./vendor/bin/phpunit
